### ISSUE TITLE
Doesn't encrypt a unique: true field in mongoose schema

### ISSUE THREAD

**Issue by MohRaouf** [joegoldbeck/mongoose-encryption#114]
As the issue title, everything was working great until I set a field in mongoose schema as unique, when I took a look at the DB, I could see that field not encrypted anymore.

**for sure I tried to drop the collection and start over, but the issue persists**

**Comment by joegoldbeck** [comment]
Hi @MohRaouf this is expected behavior. The encryption is such that the same value stored multiple times would have different results, so there would be no way to enforce a unique constraint on the data. (The reason is to protect against various kinds of collision attacks) Thus, a field may encrypted or unique, but not both

**Comment by MohRaouf** [comment]
> Hi @MohRaouf this is expected behavior. The encryption is such that the same value stored multiple times would have different results, so there would be no way to enforce a unique constraint on the data. (The reason is to protect against various kinds of collision attacks) Thus, a field may encrypted or unique, but not both


I understand and actually, I expected that it's a logical explanation, but please consider mention that in the documentation to make everything clear for the others,

Thank you bro 🙏
