### ISSUE TITLE
Using larger keys (such as 2048 bit certificates)

### ISSUE THREAD

**Issue by PeteDaGuru** [joegoldbeck/mongoose-encryption#18]
Wondering if you've dealt with requirements to use larger key sizes ?  AES256 is standard for data transfer after initial keys are negotiated (e.g. with SSL), but requirements for data-at-rest in a database can be much higher.     Have you done any benchmarking or analysis about performance with different keysizes?

  For organizations that would like to manage storage keys via certificates rather than other kinds of shared secrets, a simple change  would be to use crypto.publicEncrypt/privateEncrypt with a given public/private keypair.   Performance would most likely suffer unless the platform crypto implementation was well-tuned, but since this is often performed as part of SSL anyways, we may be able to take advantage of optimizations that already exist to support those other usages.
   Use of public/private keys might also open the possibility to allow only some clients write access, with others allowed to read the data.

**Comment by joegoldbeck** [comment]
I haven't dealt with larger keysizes - as far as I can tell AES256 is the largest key supported by simple cipher/decipher methods in the node crypto module, and I hadn't thought much about using crypto.publicEncrypt/privateEncrypt. Generally my preference is to keep things simple unless there's an essential use case for doing otherwise.

A brief google suggests that AES-256 is standard and sufficent for data-at-rest applications. For example: https://www.owasp.org/index.php/Cryptographic_Storage_Cheat_Sheet#Rule_-_Use_strong_approved_cryptographic_algorithms . Do you have a specific source you're referring to which suggests that larger keys are required?

**Comment by PeteDaGuru** [comment]
I have a mandate that says that all encryption must be "2048 bits" ... basically, a bureaucratic fiat, that requires explanations and justifications to avoid.    Beyond the "more key bits are better for security" driver, there is also an organizational driver:  managing and doling out "keys" using standard certificates makes administration and tracking easier.   Auditing can say "we use a standard approved certificate as our key" rather than some odd pair of custom strings.
   I think I can make an argument that most standard full-disk encryption uses 256-bit keys at best, so we're going above and beyond by using larger keys.  Perhaps just using the 2048-bit key to help generate the internal keys might satisfy the mandate.    Using it that way doesn't add any extra fundamental cryptographic security,  it but it does add some obfuscation between what is in config files/environment variables and what is actually used when reading/writing the database.

**Comment by joegoldbeck** [comment]
Seems reasonable. If you use the [`secret` parameter] (https://github.com/joegoldbeck/mongoose-encryption#secret-string-instead-of-two-keys) instead of the keys, you can pass in a string of any length, so you could just pass in your 2048-bit key right there!
