### ISSUE TITLE
Data loss when asynchronously save twice

### ISSUE THREAD

**Issue by globlee** [joegoldbeck/mongoose-encryption#26]
Since I started using this software I have been losing a lot of data. The documents are still in my database, but I cannot find them with the mongoose client. after that I switched to only encrypt certain fields, and now only these encrypted fields are being lost. I am encrypting schema defined objects in my document. 
Is there anything I could be doing that would cause this? I don't know what causes this, I am trying to figure that out, however I am not getting any errors about this. I think it is probably something wrong on my end, because I'm sure if this was a normal thing people would have reported this before,  but I cannot figure out what because I am not doing anything unusual with mongo or mongoose, just finding and saving really. Do you have any suggestions as to how to debug this?

**Comment by joegoldbeck** [comment]
To clarify, when you retrieve documents (say, querying by `_id`), are the encrypted fields still missing?

A couple notes that might clear things up:
- If a field is encrypted, you can't query that database on that field, since it's encrypted and packed into the `_ct` field. You can only query on unencrypted fields. (Fields that are only authenticated are fine though). 
- If you use the `lean` option in Mongoose, the decryption middleware doesn't run and the data remains encrypted inside `_ct`

**Comment by globlee** [comment]
"To clarify, when you retrieve documents (say, querying by _id), are the encrypted fields still missing?"

Yes. I am now able to reproduce this I believe. It happens after I save the document, but the document gets saved twice due to poor design of code. I am fixing that part, and will test if that was the problem

**Comment by joegoldbeck** [comment]
Hmmm that could potentially be the issue. Saving a document, and then saving it again after the first save completes should work fine since the document is decrypted in the `post-save` Mongoose hook. However, I could imagine that saving the same document twice asynchronously might cause some issues.

Please let me know if that is indeed the issue!

**Comment by globlee** [comment]
Yes I was able to stop it saving twice and it no longer occurred, and then undo the changes and it happened again. I was saving the user document which s used by expressjs, so that interaction could be affecting it as well.

**Comment by globlee** [comment]
Well the same thing just happened, I lost all the data that was in the encrypted sub-objects, only. I will try to see what caused it this time and post back.

**Comment by globlee** [comment]
Its possible the following code is responsible, but I don't really think the following code is necessarily wrong. Never the less I will restructure it. but if this is the problem then it seems this could be a pretty dangerous bug if the user happened to be saved twice from different operations at the same time. Again I cannot reproduce this, ostensibly because both the callbacks here don't usually fire the save at the same time, but it did happen the one time when I re-opened this case that they did. I also could have something wrong with my mongoose or mongodb settings maybe, I will look into that in the future.

					graph.get("/me/friends", function(err, res) {
						user.save(function(err) {
					        if (err){
					        	console.log(err, "error buildprofile.js");
					        }
					    });
					});
					graph.get("/me", function(err, res) {

						user.save(function(err) {
					        if (err){
					        	console.log(err, "error buildprofile.js");
					        }
					    });


					});

**Comment by globlee** [comment]
I will leave this open so that you can see it then you can close it when you have read it.

**Comment by joegoldbeck** [comment]
Thanks for the report!

Yeah that is probably what is responsible. You're getting some weirdness because your server is stateful and (somewhat necessarily because it's node) async. Typically the server might be stateless and the user would get retrieved from the database separately for each request, rather than having a more global user object. This would prevent the problem since `user` would refer to a different object in either case. Alternatively, you'd need some sort of locking mechanism to prevent this kind of collision. Typically the database would handle this, but since encryption is being handled in the app layer, we can't rely on the locking mechanisms provided by Mongo.

Worth noting that even if the app is stateless, there is a chance that if requests are coming in very quickly editing the same document, one set of changes to a group of encrypted fields could potentially be overwritten by changes to another group of encrypted fields, since they are all bundled in a single `_ct`  field (and authenticated with a single `_ac` field). This won't cause simple data loss like you're seeing, but you could find that changes you thought were saved actually got displaced. Haven't heard any reports of this in the wild yet though.
