### ISSUE TITLE
Request: Retroactive bump of 0.x to support node 5

### ISSUE THREAD

**Issue by burtonjc** [joegoldbeck/mongoose-encryption#31]
Hi @joegoldbeck,

We have a migration framework to keep the DBs in our various environments up to date. Our older migrations are pinned to mongoose-encryption `0.x` because the DB at that time was running on `0.x`. We want to upgrade our migration framework to use node 5, but we can't do that unless those `0.x` dependent migrations can use node 5. Long story short, we need a `0.x` version that supports node 5. Any chance you would be willing to publish one?

**Comment by joegoldbeck** [comment]
Yeah this should be totally doable. There's the only change on this end is https://github.com/joegoldbeck/mongoose-encryption/commit/c2a36b5adc596459a818fa61cfb7c4563d5fccdf. You'll also have to bump the version of Mongoose so that it's >=4.2.4 . Which `0.x`'s would you like a bump for?

**Comment by joegoldbeck** [comment]
Added a check for version compatibility of Mongoose and Node in https://github.com/joegoldbeck/mongoose-encryption/commit/4f500ea87baed2f1ec364b5bfab62e2c25a8f769 . And declared Mongoose as a peer dependency so that check should work correctly in https://github.com/joegoldbeck/mongoose-encryption/commit/856e4ca7acc0bf04317256d37ee99845e4b62e42

**Comment by burtonjc** [comment]
That sounds great @joegoldbeck! `0.13.1` would be perfectly fine for us. I opened an issue on our end to get around to opening the PR. We have planning today and that will determine when we could pull that work. Thanks!

**Comment by joegoldbeck** [comment]
Looking a little closer, if that's all you need, I don't think there significant breaking changes between 0.13.0 and the current version (1.2.3). The 1.0 release was just to declare the API stable. The major breaking change was at 0.12.0 (when authentication was added), so if you already have upgraded at least that far, you should be fine to upgrade to the latest version. If there's an issue you're running into with that, or you need a version <=0.11, please reopen and let me know.

**Comment by burtonjc** [comment]
Ah, I didn't realize 0.12 is when authentication was added. Yeah, we would actually need a version before authentication was implemented. Looks like I can't reopen the issue though.

**Comment by joegoldbeck** [comment]
Ok, so you'd need 0.11.1, yeah? I'll see what I can do!

**Comment by burtonjc** [comment]
Thank you @joegoldbeck!

**Comment by joegoldbeck** [comment]
Released as [0.11.1](https://github.com/joegoldbeck/mongoose-encryption/tree/0.11.1). 

Tried to include all relevant bug fixes that came after 0.11.0. Didn't include the test refactor done for Mongoose 4.1.x in 7e12f6a1e93a5b4e623153ed2f9f7811def42728, since all tests were passing on my end on the latest version of Mongoose, but otherwise I believe all non-authentication-related fixes are included.

Definitely test this on your own systems, using whatever versions your deployed with, before deploying. 

Hope this helps! Let me know if you run into issues.

**Comment by burtonjc** [comment]
This is great! Thank you a ton for the support, and I'll let you know if anything comes up!
