### ISSUE TITLE
Allow encryption of individual fields.

### ISSUE THREAD

**Issue by mrjonny2** [joegoldbeck/mongoose-encryption#34]
Allow mongoose-encryption to be completely transparent by having every field individually encrypted as an option even though this may be extremely computationally intensive for writing of the document initially, in some cases it may be required

**Comment by joegoldbeck** [comment]
Hey @mrjonny2 thanks for the feature request! The decision to encrypt (and authenticate) all the fields at once was a core decision (primarily made for simplicity, since that makes it easier to reason about potential security holes in the overall scheme, as well as check the code for bugs that could compromise security ) - I think deviating from it would require a pretty major rewrite. I think this is probably a `wontfix` . Is there a specific use case you have in mind that isn't covered when all the encrypted fields are in a single chunk?

**Comment by mrjonny2** [comment]
Hey @joegoldbeck 
It may be me misunderstanding the way the library works so please correct me if I am wrong.  

If I encrypt all of a users contact details when they create an account as an example below, phone and email from the document below will be encrypted together.
`{
    name: blah,
    phone: 12345,
    email: blah@blah.com
}`

So if I were to query the db asking for a list of all my users email addresses I would have to query the phone and email addresses, decrypt them and then filter the documents individually on my application server.  This could be a little problematic especially if you want to keep certain information from reaching the application server because the user may not have access to it.

**Comment by joegoldbeck** [comment]
That's right. You'll potentially be loading data on the application server that you don't want exposed. It's then up to the application to enforce access control rules. If I understand correctly, the difficulty here is that you can't use the query itself (say, via `select`) to enforce this access control. Rather, you need to pick out the fields you want to expose _after_ the document is retrieved. So, that is perhaps more awkward. Do I understand correctly?

**Comment by mrjonny2** [comment]
Yes that is one of the applications that I can think of.  This also increases the load on the DB for every query as they will often be larger than than is actually required.  As I have always thought, it is better to only pull the data that you need rather than pull everything and filter in the application server.  It increases the load on all the components in the system for general use where you aren't pulling all the data.

Whereas if you encrypt fields individually you maintain a low load on the DB server which is preferable.

**Comment by joegoldbeck** [comment]
Yep, totally see where you're coming from. Thanks for the suggestion and conversation! I think, since it's not a dealbreaker for security, and keeping the plugin stable, up-to-date, and backwards-compatible for existing users is high priority, this is a change that won't happen in the near term. I think, effectively, it would require a full re-write of the plugin and tests. I'd prefer to see (don't have time to write it at the moment) a different plugin specifically designed for encrypting fields individually, rather than have two major code paths within this single plugin (since it's security-focused, I want the fewest code paths possible).

Note that one thing you lose with the "individual field" method is straight-forward document-level authentication. An attacker with write-access could delete one of the encrypted fields from the document, and you wouldn't have a way of recognizing that the document had been modified, without some more complex authentication scheme.

**Comment by mrjonny2** [comment]
That is fair enough.  You do make a valid point on the last part though.  I guess the solution to that would be to store a signature for each document to prevent that happening along with the individually encrypted fields
