### ISSUE TITLE
How can I migrate encrypted field to unencrypted field safely?

### ISSUE THREAD

**Issue by johntangma** [joegoldbeck/mongoose-encryption#40]

**Comment by joegoldbeck** [comment]
If you just update the options for the plugin so that the field will no be longer encrypted, then every time you save a document that field will be unencrypted. Decryption will still work fine though :) So, just update the options, and then find and save each document in turn without editing it. Let me know if you run into any issues.

*Always* back up your database before doing anything like this though, just to be safe.
