### ISSUE TITLE
Query on data has bad performance

### ISSUE THREAD

**Issue by ssgoldenman** [joegoldbeck/mongoose-encryption#45]
Hello all,
I am using mongoose-encryption in one of my project to have db encryption. Everything works well with a small set of documents. However if i try:
`model.find({},function(err,data){
})`
it takes over 2 minutes for a records size of 30000. When i use the .lean() function the query executes in less then a second however when it decripts the data it takes more time. At certain point the node runs out of memory during the operation. I was not able to find any tickets that relate to this issue, so i am wondering if i am doing something wrong?
Regards

**Comment by joegoldbeck** [comment]
Hi @ssgoldenman - thanks for filing the issue! ~5 ms to decrypt and authenticate each document does seem slow, but also not out of the question. How large are your documents? Are you using any other mongoose plugins or just this one?

**Comment by ssgoldenman** [comment]
Hello @joegoldbeck - thanks for the response. I don't use any other plugins. The documents are small around 10-15kb each. I leave 1 value in plain text to be able to query against it and the rest is encrypted. My issue is that is extremely slow with 30000 records, i have event tested it for 10000 and its about more then one minute. Have there been any other reports about this issue from people that are dealing with larger amounts of data?

**Comment by joegoldbeck** [comment]
I haven't received any other reports, but I suspect typical usage involves fetching smaller numbers of documents at a time. Sounds like some [profiling](https://nodejs.org/en/docs/guides/simple-profiling/) is in order.

**Comment by joegoldbeck** [comment]
Just wanted to give a quick update after I took a first pass at looking into this. On my local, I'm finding it takes about 1.5ms / document, about two-thirds of this seems to be due to the plugin (decrypting and authenticating in the init hook in particular), but the rest is due to other things that Mongoose does to create the Mongoose document objects.

```
Finding 10000 documents with an average size of 16KB each

with plugin           15222ms
without plugin        5410ms
with lean option      1639ms
```

Where is the CPU going?
```
Self      Total
22.83 %   22.83 %   (garbage collector)	
10.97 %	12.75 %   MongooseArray	
8.26 %    8.26 %    Hash.update (called from computeAC)
6.33 %    8.59 %    stringify 	(called from json-stable-stringify inside computeAC)
6.11 %    7.05 %    Cipher.update	(called from decryptSync)
3.43 %	12.78 %	schema.methods.decryptSync	
2.61 %	2.61 %	exports.decorate
2.38 %	2.40 %	Buffer.toString (largely called from stringify, above)
```

One possibility I checked for speeding things up is making the decryption in the `init` middleware asynchronous by using the asynchronous `.end` method instead of the `.update` method for deciphering the cryptotext. However, this didn't result in time savings, and simply replaced `Cipher._transform` for `Cipher.update` above.

**Comment by joegoldbeck** [comment]
If anyone comes up with a good way to increase performance, I'm all ears. Closing until that point.
