### ISSUE TITLE
 How to decrypt an encrypted field

### ISSUE THREAD

**Issue by muhammadfaizan** [joegoldbeck/mongoose-encryption#48]
Is there a possible way to decrypt a field that I encrypted earlier ?

**Comment by joegoldbeck** [comment]
If you update the options so that the field will no longer be encrypted, then when you find a document, it will still be decrypted, but when you go to save it again, it will remain unencrypted and be persisted as cleartext.

So, if you want to do that for your whole collection, you could update the options, and then run a script to find documents where that field doesn't exist (using `$exists`) and then save them. If you are going to do this without downtime, it is likely safest to do this one at a time or in small batches. As always, back everything up beforehand just in case.

**Comment by muhammadfaizan** [comment]
Hey thanks, thats a great way of doing it, Thanks a Bunch :)

**Comment by muhammadfaizan** [comment]
If I can be of any service to You, I'd be thankful I can help, your module has helped me greatly.
