### ISSUE TITLE
findBy in decrypt callback

### ISSUE THREAD

**Issue by cAstraea** [joegoldbeck/mongoose-encryption#72]
Is there a way to hook into this .decrypt method for findOne etc? 

The encryption is enabled on the schema 
AccountSchema.plugin(encrypt, {
	encryptionKey: encKey,
	signingKey: sigKey
})

For example have a function that searches for email this doesn't work if the encryption is turned on.
AccountSchema.statics.findByEmail = async function (email) {
	try {
		const account = await this.findOne({
			email: email
		})	
		return account
	} catch (err) {
		return null
	}
}

How can I use the findOne inside the decrypt callback ?

**Comment by cAstraea** [comment]
Hello. Something is not clear though ... 

From the docs : 
find works transparently (though you cannot query fields that are encrypted) and you can make New documents as normal, but you should not use the lean option on a find if you want the document to be authenticated and decrypted. findOne, findById, etc..., as well as save and create also all work as normal.  
What does this mean exactly ? I have a doc where my field is probably hidden in _ct and_ac thingies. 
doing
```
const account = await this.findOne({
			ct
		})
```
 returns null . Is this the expected behavior ?

**Comment by joegoldbeck** [comment]
Hi @cAstraea thanks for filing the issue! This is actually expected behavior. Because the field is encrypted, it is not queryable. You can use the `excludeFromEncryption` option if you want certain fields to be available to search by. Once you find a document based on a query which does _not_ include encrypted fields, it will be decrypted as part of the find middleware
